### ISSUE TITLE
Password protected zips?

### ISSUE THREAD

**Issue by CyrosX** [uktrade/stream-unzip#15]
Are password Password protected zips supported?
Did not find any information about this.

**Comment by michalc** [comment]
@CyrosX Not at the moment (and can't really promise if/when they will be)

**Comment by michalc** [comment]
@CyrosX Support now added (via https://github.com/uktrade/stream-unzip/pull/16/files)

Note that this just supports the weak/historical password protection of zip files. AES encryption is not supported (yet...)

**Comment by michalc** [comment]
I'm going to close the ticket: I believe password support is now added.

For AES/other, feel free to open another issue
