### ISSUE TITLE
Not iterating all chunks explicitly causes signature error

### ISSUE THREAD

**Issue by jeroenbaas** [uktrade/stream-unzip#21]
I stumbled on a bug while trying to see if smart_open would work: if you do not iterate all chunks ("unzipped_chunks") there will be a signature error:
```python
from stream_unzip import stream_unzip, UnexpectedSignatureError
import smart_open

url="https://transfer.sh/get/cp4LTN/test.zip"

print("without chunk iteration")
try:
    with smart_open.open(url,'rb') as f_h:
        for file_name, file_size, unzipped_chunks in stream_unzip(f_h):
            print(file_name)
except UnexpectedSignatureError as e:
    print("UnexpectedSignatureError: "+str(e))

print("with chunk iteration")
try:
    with smart_open.open(url,'rb') as f_h:
        for file_name, file_size, unzipped_chunks in stream_unzip(f_h):
            print(file_name)
            for chunk in unzipped_chunks:
                continue
except UnexpectedSignatureError as e:
    print("UnexpectedSignatureError: "+str(e))
```

result:
```sh
$ python .\stream_unzip_test.py
without chunk iteration
b'test.txt'
UnexpectedSignatureError: b'test'
with chunk iteration
b'test.txt'
b'test1.txt'
b'xsubtest.zip'
```

**Comment by michalc** [comment]
Hello again! 👋 

So something has to iterate over the chunks of each file to get to the next file…

… and I’m tempted to make it requirement that client code has to do it, and at most see if the exception can be clearer if the client code doesn’t. Essentially to not have code in this library that isn’t for its main purpose (getting at the unzipped bytes of all files) that could live outside it.

**Comment by jeroenbaas** [comment]
I can appreciate the desire to not touch this, however it feels counter-intuitive to _have_ to iterate. To the API user, there is no action in the iteration, it just looks like collection.
Here's a use case: say I have a zip with loads of files. I know files by pattern that I need to process. The rest I don't care about. In those cases you may want to take a pass on iterating over the chunks and move to the next file. Of course in the background, since we're streaming, something has to advance the pointer to the next file in the zip. 

since the stream_zip return suggests it is iterating over the files and not the chunks by the way it is designed, to me it looks more logical to have this done in the api. The alternative would be to not return an iterator per file, but first an iterator of the chunks, and within each chunk return the file name.

**Comment by michalc** [comment]
As per https://github.com/uktrade/stream-unzip/pull/23, stream-unzip should now raise a clearer iteration, UnfinishedIterationError, if the bytes of a member file are not fully iterated over

(And as per explanation above, there is no plan to change the API to allow client code to _not_ iterate over all the bytes. Client code must iterate over all the bytes, or UnfinishedIterationError will be raised)
