### ISSUE TITLE
Error uncompressing a Zip64 file

### ISSUE THREAD

**Issue by rustyconover** [uktrade/stream-unzip#32]
When decompressing a Zip64 file this error is raised:

```
stream_unzip.UnexpectedSignatureError: b'8\\\x12]'
```

Have you encountered this before?

Thanks,

Rusty

**Comment by michalc** [comment]
Ah no. Can you share the file / show how it was made? (ideally _exactly_ how it was made so I can have the exact same bytes at my end)

**Comment by rustyconover** [comment]
Sadly I can't share it, but thanks for the heads up.

I've had some decent success now combining smart_open with the ZipFile module.  Your module is pretty great though.

**Comment by michalc** [comment]
Ah understood. Will close this issue for now, but if you end up being able to share more details, feel free to reopen.

**Comment by michalc** [comment]
@rustyconover So you know, another user reported a [similar error for files known to be created by Java](https://github.com/uktrade/stream-unzip/issues/33). Which not all problems have been fixed, a good amount of them have been by https://github.com/uktrade/stream-unzip/pull/34
