### ISSUE TITLE
Issue when extracting zip made using in-built Windows 11 tool

### ISSUE THREAD

**Issue by sai3563** [uktrade/stream-unzip#51]
Hi,

I had written a small piece of code that successfully extracts zip files in chunks using stream-zip. When I was testing, I was zipping files using WinRAR.

However, I received a zip file from a colleague on which, the same code didn't work.

The code:

```
from stream_unzip import stream_unzip
import boto3

def zipped_chunks():
    yield from boto3.client('s3', region_name='us-east-1').get_object(
        Bucket='my-bucket-name',
        Key='the/key/of/the.zip'
    )['Body'].iter_chunks()

for file_name, file_size, unzipped_chunks in stream_unzip(zipped_chunks()):
    for chunk in unzipped_chunks:
        print(chunk)
```

I got the below error:

```
Jun 22 05:40:04 ip-192-29-240-283 uvicorn[1067084]:   File "/home/ubuntu/venv/lib/python3.8/site-packages/stream_unzip.py", line 459, in stream_unzip
Jun 22 05:40:04 ip-192-29-240-283 uvicorn[1067084]:     for file_name, file_size, unzipped_chunks in stream_unzip(zipped_chunks()):
Jun 22 05:40:04 ip-192-29-240-283 uvicorn[1067084]:   File "/home/ubuntu/venv/lib/python3.8/site-packages/stream_unzip.py", line 457, in all
Jun 22 05:40:04 ip-192-29-240-283 uvicorn[1067084]:     raise UnexpectedSignatureError(signature)
Jun 22 05:40:04 ip-192-29-240-283 uvicorn[1067084]: stream_unzip.UnexpectedSignatureError: b'----'
```

On further exploration, I found out that the zip file was made using Windows 11. In Windows 11, one can make zip files by selecting multiple files in file explorer, right clicking and selecting "Compress to ZIP file".

Here are sample files, one that works i.e. made using WinRAR and another that doesn't i.e. made using Windows 11.

[products_working.zip](https://github.com/uktrade/stream-unzip/files/11827360/products_working.zip)
[products_not_working.zip](https://github.com/uktrade/stream-unzip/files/11827361/products_not_working.zip)

Both files are exactly of the same size, but there is a subtle difference in the way they are displayed in WinRAR.
`products_working.zip - ZIP archive, unpacked size 1,059,090 bytes`
`products_not_working.zip - SFX ZIP volume, unpacked size 1,059,090 bytes`

I believe it is due to headers being set to SFX ZIP volume by Windows 11.

I was wondering if there is a way to fix this? As our clients mostly use Windows, it would be quite hard to inform everyone to use winrar/7zip over the built in tool.

**Comment by michalc** [comment]
Hi @sai3563, thanks for the report.

> I believe it is due to headers being set to SFX ZIP volume by Windows 11.

Will have a nose around. But my first instinct is very similar to this. I have to admit a lot of ignorance, but I guess SFX means self extracting? So it would include code at the beginning of the file that extracts the zip data in the remainder of the file. stream-unzip assumes the zip data is at the beginning.

It’s interesting that this is the default in Windows 11. Have to admit I had no idea this was the case.

**Comment by sai3563** [comment]
@michalc Thanks for the quick reply. I got access to a machine with Windows 11. (Previously was working on Windows 10 with WSL.) When I created zip file using the right click context menu, the zip file was generated properly and stream-unzip was able to extract it.

So, how exactly that file which is not working got generated is a mystery.

The weird thing is, both files have the exact size, up to the byte level, so I don't think they are any different other than the headers.

You are right with the definition of SFX, but if it really had code to self extract, one would assume it would at least add 1 byte?

The application I'm going to build will be used by many third party clients, so I do have a feeling I'm going to run into this issue again sometime. For this sake, I hope it's relatively easy to fix/workaround. I will update if I get more clarity on this.

**Comment by michalc** [comment]
> You are right with the definition of SFX, but if it really had code to self extract, one would assume it would at least add 1 byte?

They seem to be different sizes to me!

```
1042229 22 Jun 20:58 products_not_working.zip
1041554 22 Jun 20:58 products_working.zip
```

I wonder how other streaming unzippers deal with this. For example https://github.com/madler/sunzip or libarchive, say via https://stackoverflow.com/a/74986842/1319998 ...

**Comment by michalc** [comment]
I'm starting to suspect this is not an SFX archive. From the beginning of `hexdump -C` on the file:
```
00000000  2d 2d 2d 2d 2d 2d 2d 2d  2d 2d 2d 2d 2d 2d 2d 2d  |----------------|
00000010  2d 2d 2d 2d 2d 2d 2d 2d  2d 2d 2d 2d 38 38 37 30  |------------8870|
00000020  33 39 36 34 36 38 38 30  34 32 32 36 33 30 30 38  |3964688042263008|
00000030  38 32 35 34 0d 0a 43 6f  6e 74 65 6e 74 2d 44 69  |8254..Content-Di|
00000040  73 70 6f 73 69 74 69 6f  6e 3a 20 66 6f 72 6d 2d  |sposition: form-|
00000050  64 61 74 61 3b 20 6e 61  6d 65 3d 22 22 3b 20 66  |data; name=""; f|
00000060  69 6c 65 6e 61 6d 65 3d  22 41 43 4f 54 4f 33 32  |ilename="ACOTO32|
00000070  30 2e 7a 69 70 22 0d 0a  43 6f 6e 74 65 6e 74 2d  |0.zip"..Content-|
00000080  54 79 70 65 3a 20 61 70  70 6c 69 63 61 74 69 6f  |Type: applicatio|
00000090  6e 2f 7a 69 70 0d 0a 0d  0a 50 4b 03 04 14 00 00  |n/zip....PK.....|
```
and from the end
```
000fe6a0  43 4f 54 4f 34 31 32 2e  70 6e 67 50 4b 01 02 14  |COTO412.pngPK...|
000fe6b0  00 14 00 00 00 08 00 95  b3 b3 56 23 e3 8f ee 02  |..........V#....|
000fe6c0  06 03 00 77 09 03 00 0c  00 00 00 00 00 00 00 00  |...w............|
000fe6d0  00 20 00 00 00 fe de 0c  00 41 43 4f 54 4f 34 32  |. .......ACOTO42|
000fe6e0  33 2e 70 6e 67 50 4b 05  06 00 00 00 00 05 00 05  |3.pngPK.........|
000fe6f0  00 22 01 00 00 2a e5 0f  00 00 00 0d 0a 2d 2d 2d  |."...*.......---|
000fe700  2d 2d 2d 2d 2d 2d 2d 2d  2d 2d 2d 2d 2d 2d 2d 2d  |----------------|
000fe710  2d 2d 2d 2d 2d 2d 2d 2d  2d 38 38 37 30 33 39 36  |---------8870396|
000fe720  34 36 38 38 30 34 32 32  36 33 30 30 38 38 32 35  |4688042263008825|
000fe730  34 2d 2d 0d 0a                                    |4--..|
```
It's looking a bit like something like the raw POST of a form upload. Looking at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#examples it's very similar to one of its examples:

```
POST /test.html HTTP/1.1
Host: example.org
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="field1"

value1
--boundary
Content-Disposition: form-data; name="field2"; filename="example.txt"

value2
--boundary--
```
So my suspicion right now is that this was uploaded via an HTTP server that isn't properly processing the upload.

**Comment by sai3563** [comment]
@michalc The file was uploaded to S3 using a pre-signed URL. (It is basically an unauthenticated temporary URL that allows u to upload a file to S3). REST API PUT request is used for the same. Do u think some wrong parameter was used during the upload?

**Comment by michalc** [comment]
> Do u think some wrong parameter was used during the upload?

Hmmm... I don't know I have to admit. Nosing around the data, I notice this:

```
name=""
```
does this have to have a name, e.g. `file`? Looking at https://fourtheorem.com/the-illustrated-guide-to-s3-pre-signed-urls/ as well, could this be submitted via a PUT, which I think interprets the bytes exactly as submitted (which seems to be what is happening here), when actually, it should be a POST? I'm guessing here.

Are you able to share the HTML for the form that uses the pre-signed URL?

**Comment by sai3563** [comment]
@michalc ok I figured out the issue.

Apparently the person who uploaded the file to S3 selected form-data in Postman instead of binary, which caused the issue. 😅

![image](https://github.com/uktrade/stream-unzip/assets/113760738/8cef4936-9b82-4a8b-b549-ec5aec75696f)

So it was not a Windows 11 bug, but "wrong option selected in Postman" bug. Sorry for the confusion. 😅 The process isn't under my control end to end so debugging errors sometimes is not so straightforward.

I will close this for now and reopen a new issue if I find a legit bug.
