### ISSUE TITLE
Not working with pyarrow on S3

### ISSUE THREAD

**Issue by bfaust-bp** [uktrade/stream-unzip#94]
Hi

I have a zipped CSV in an AWS S3 bucket and use Pyarrow to read it from there.
So, after opening the S3 file as a stream and calling stream_unzip, I got an error because the Pyarrow NativeFile class doesn't return anything in __next__.

My code is:

```
from io import BytesIO
from boto3.session import Session
from pyarrow import fs, csv
from stream_unzip import stream_unzip

aws_session = Session()
aws_session_credentials = aws_session.get_credentials()
aws_session_frozen_credentials = aws_session_credentials.get_frozen_credentials()  # type: ignore

s3_fs = fs.S3FileSystem(
    access_key=aws_session_frozen_credentials.access_key,
    secret_key=aws_session_frozen_credentials.secret_key,
    session_token=aws_session_frozen_credentials.token,
    region=aws_session.region_name,
)

buffer = BytesIO()
with s3_fs.open_input_stream("my_bucket/zipped_csv.zip", buffer_size=65536) as s3fp:

    for file_name, file_size, unzipped_chunks in stream_unzip(s3fp):
        for chunk in unzipped_chunks:
            buffer.write(chunk)

buffer.seek(0)
df = csv.read_csv(buffer)
buffer.close()

print(df)
```

If you run this simple code, you will get an error on stream_unzip.next_or_truncated_error because the "_next = next(it)" returns empty bytes.

So, I made a simple change in the code of stream_unzip.next_or_truncated_error to work with Pyarrow:

```
    def next_or_truncated_error(it):
        try:
            if type(it).__name__ in ("NativeFile", "BufferedInputStream"):
                _next = it.read1(chunk_size)
                if not _next:
                    raise StopIteration
            else:
                _next = next(it)
            return _next
        except StopIteration:
            raise TruncatedDataError from None
        except Exception as e:
            print(f"Error: {e}")
            return None
```

What do you think about that?

Can you add something like this to your code or expose the stream_unzip.next_or_truncated_error to be patched?

Thanks

**Comment by michalc** [comment]
Hi @bfaust-bp,

Thanks for the report

> you will get an error on stream_unzip.next_or_truncated_error because the "_next = next(it)" returns empty bytes.
> ...
> Can you add something like this to your code or expose the stream_unzip.next_or_truncated_error to be patched?

Will have a ponder... it _is_ documented at https://stream-unzip.docs.trade.gov.uk/get-started/ that the iterable has to have no zero length chunks, and I kinda think returning empty bytes instances is "broken" behaviour of the data source. But understood that it might be a bit of a gotcha...

In the meantime you don't need to patch stream-unzip to fix it, you can add in an intermediate generator to filter out the zero length ones:
```
for file_name, file_size, unzipped_chunks stream_unzip((chunk for chunk in s3fp if chunk))
    ...
```

**Comment by michalc** [comment]
>  I got an error because the Pyarrow NativeFile class doesn't return anything in next.

Actually I wonder if I've misunderstood...  does it _never_ return anything in next, because it's not an iterable/not a well behaved one?

If so, could do something like this:
```python
for file_name, file_size, unzipped_chunks in stream_unzip(iter(lambda: s3fp.read(65536), b''))
    ...
```
If still I've misunderstood, would be good to know precisely what error is raised (I don't think you mentioned it in the original post)

**Comment by michalc** [comment]
> Can you add something like this to your code or expose the stream_unzip.next_or_truncated_error to be patched?

To answer this, I'm now leaning to _no_, because I suspect this can be handled fine outside of stream_unzip by either filtering out zero length chunks, or by using the iter function to convert a file-like object to an iterable.

**Comment by michalc** [comment]
Will close this soon since I suspect it can be addressed without changes to stream-unzip
